<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<?php
/**
 * @var \Modules\ExchangeRate\Block\ExchangeRateBlock $block
 */
?>

<?php
$ch = curl_init();
$headr = array();
$url = "https://portal.vietcombank.com.vn/Usercontrols/TVPortal.TyGia/pXML.aspx?b=8";

curl_setopt($ch, CURLOPT_HTTPHEADER, $headr);
curl_setopt($ch, CURLOPT_URL, $url ); // get the url contents
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch,CURLOPT_USERAGENT,'spider');

$get = curl_exec($ch); // execute curl request
curl_close($ch);

$xml = simplexml_load_string($get);
$con = json_encode($xml);
$data = json_decode($con, true);
?>
<h3 class="text-center">Tỉ giá ngoại tệ Vietcombank <?= $data['DateTime'] ?></h3>
<table class="table">
<thead style="background-color:#d1d1d1">
    <tr>
        <th scope="col"><h3>STT</h3></th>
        <th scope="col"><h3>Mã</h3></th>
        <th scope="col"><h3>Tên ngoại tệ</h3></th>
        <th scope="col"><h3>Giá mua</h3></th>
        <th scope="col"><h3>Giá bán</h3></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($data['Exrate'] as $k => $currency): ?>
    <tr>
        <td style="font-size: 1.25rem; vertical-align: middle" scope="row"><h5 ><?= $k+1 ?></h5></td>
        <td style="font-size: 1.25rem;">
    <?php
    $currencyCode = $currency['@attributes']['CurrencyCode'];

    if (strpos($currencyCode, 'EU') !== false) {
        // Nếu chuỗi chứa "EU"
        $flagSrc = 'https://flagcdn.com/h60/eu.png';
        $flagAlt = 'EUR';
    } else {
        // Nếu chuỗi không chứa "EU"
        $flagSrc = 'https://flagsapi.com/' . substr($currencyCode, 0, -1) . '/flat/64.png';
        $flagAlt = $currencyCode;
    }
    ?>

<img src="<?= $flagSrc ?>" width='64px'  alt="<?= $flagAlt ?>">
    <?= $currencyCode ?>
</td>
        <td  style="font-size: 1.25rem; vertical-align: middle"><h5><?= $currency['@attributes']['CurrencyName'] ?></h5></td>
        <td><h5><?= $currency['@attributes']['Buy'] ?></h5></td>
        <td><h5><?= $currency['@attributes']['Sell'] ?></h5></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
