<style>
    .box-news {
        clear: both;
        display: table;
        width: 100%;
        border-bottom: solid 1px;
        padding: 20px 0px;
    }
    img {
        float: left;
        padding-right: 20px;
        width: 150px;
        height: 150px;
    }
    div p {
        color: black;
    }
</style>
<?php
    $news = $block->getNews();    
?>
<?php
    foreach($news->channel->item as $items) {
?>
    <a href="<?php echo $items->link ?>" target="_blank">
        <div class="box-news">
            <img src="<?php echo $items->image ?>" alt="<?php echo $items->title?>">
            <div>
                <h3><?php echo $items->title ?></h3>
                <p><?php echo $items->description ?></p>
            </div>
        </div>
    </a>
<?php
    } 
?>