<?php
/**
 * @var $helper \Meetanshi\FacebookChat\Helper\Data
 */
$helper = $this->helper('Meetanshi\FacebookChat\Helper\Data');

$enable = $helper->isEnable();
$appId = $helper->getFBAppId();
$pageId = $helper->getFBPageId();
$color =  $helper->getFBColor();

// @codingStandardsIgnoreLine
$color = str_replace('#', '', $color);

$pattern = "/(\d{1,3})\,?\s?(\d{1,3})\,?\s?(\d{1,3})/";

// Only if it's RGB
// @codingStandardsIgnoreLine
if (preg_match($pattern, $color, $matches)) {
    $r = $matches[1];
    $g = $matches[2];
    $b = $matches[3];

// @codingStandardsIgnoreLine
    $color = sprintf("#%02x%02x%02x", $r, $g, $b);
} else {
    $color = '#' . $color;
}

$loginText = $helper->getFBLoginText();
$logoutText = $helper->getFBLogoutText();

if ($enable) {
    if (empty($loginText)) {
        $loginText = 'Hi! What can i Help you?';
    }
    if (empty($logoutText)) {
        $logoutText = 'Hi! What can i Help you?';
    }
    ?>

    <!-- Load Facebook SDK for JavaScript -->
    <div id="fb-root"></div>
    <script>
        window.fbAsyncInit = function() {
            FB.init({
                xfbml            : true,
                version          : 'v8.0'
            });
        };

        (function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = 'https://connect.facebook.net/en_US/sdk/xfbml.customerchat.js';
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>

    <!-- Your Chat Plugin code -->
    <div class="fb-customerchat"
         attribution=setup_tool
         page_id="<?php echo $pageId;?>"
         theme_color="<?php echo $color;?>"
         logged_in_greeting="<?php echo $loginText;?>"
         logged_out_greeting="<?php echo $logoutText;?>">
    </div>
    <?php
}
?>
